// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // projectSidebar: [{type: 'autogenerated', dirName: '.'}],

  projectSidebar: [
    'projects/current-requirement',
    {
      type: 'category',
      label: 'Past',
      items: [
        'projects/past-requirements/24 Fall', 
        'projects/past-requirements/24 Spring', 
        'projects/past-requirements/23 Fall', 
        'projects/past-requirements/23 Spring', 
        'projects/past-requirements/22 Fall'
      ],
    },
  ],

  outstandingProjectsSidebar: [
    {
      type: 'category',
      label: '25 Spring',
      items: [
        'outstanding-projects/25S/group1', 
        'outstanding-projects/25S/group2', 
        'outstanding-projects/25S/group3', 
      ],
    },
    {
      type: 'category',
      label: '24 Fall',
      items: [
        'outstanding-projects/24F/group1', 
        'outstanding-projects/24F/group2', 
        'outstanding-projects/24F/group3', 
      ],
    },
    {
      type: 'category',
      label: '24 Spring',
      items: [
        'outstanding-projects/24S/group1', 
        'outstanding-projects/24S/group2', 
        'outstanding-projects/24S/group3', 
      ],
    },
  ],

  mergedPRsSidebar: [
    'merged-prs/25S',
    'merged-prs/24F',
    'merged-prs/24S',
    'merged-prs/23F',
  ],
};

export default sidebars;
